name: CI/CD Pipeline to deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: testing keys
      run: echo ${{ secrets.TEST }}

    - name: Execute remote SSH
      uses: appleboy/ssh-action@v1
      with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PVT_KEY }}
          port: 22
          script: |
            sudo npm install -g pnpm
            cd devops-test
            git pull origin main
            pnpm install
            pm2 start pnpm --name "turbo-repo" -- run start  
