name: CI/CD Pipeline to deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Execute remote SSH commands using password
      uses: appleboy/ssh-action@v1
      with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PVT_KRY }}
          port: 22
          script: ls
